version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout: 
          path: ~/examples/AlanSampleApp    
      - run:
          name: Build Sample App (from examples/AlanSampleApp)
          command: ./gradlew build