version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout      
      - run:
          name: Build Sample App (from examples/AlanSampleApp)
          # command: ./examples/AlanSampleApp/gradlew build
          command: ./examples/AlanSampleApp/gradlew assembleRelease
